In [21]:
import torch

# 1 layer network

In [22]:
x = torch.ones(5) # input tensor
y = torch.zeros(3) # expected output
w = torch.randn(5, 3, requires_grad=True) # weights
b = torch.randn(3, requires_grad=True) # bias
z= torch.matmul(x, w) + b # linear transformation
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y) # loss function:w


In [23]:
print(f'Gradient function for z = {z.grad_fn}')
print(f'Gradient function for loss = {loss.grad_fn}')

Gradient function for z = <AddBackward0 object at 0x75483ff39e40>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x75486152c1c0>


# calculation for gradient

In [24]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.3106, 0.3218, 0.0511],
        [0.3106, 0.3218, 0.0511],
        [0.3106, 0.3218, 0.0511],
        [0.3106, 0.3218, 0.0511],
        [0.3106, 0.3218, 0.0511]])
tensor([0.3106, 0.3218, 0.0511])


# not calculating for gradient

In [26]:
z = torch.matmul(x, w) + b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w) + b
    print(z.requires_grad)

True
False


In [34]:
z = torch.matmul(x, w) + b
z_det = z.detach()
print(z_det.requires_grad)
print(z.requires_grad)

False
True


jacobian product

In [35]:
inp = torch.eye(5, requires_grad=True)
out = (inp + 1).pow(2) #(1+1)^2
out.backward(torch.ones_like(inp), retain_graph=True)
print(f'Frist call \n {inp.grad}')
out.backward(torch.ones_like(inp), retain_graph=True)
print(f'Second call \n {inp.grad}')
inp.grad.zero_()
out.backward(torch.ones_like(inp), retain_graph=True)
print(f'\nCall after zeroing\n {inp.grad}')


Frist call 
 tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])
Second call 
 tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.],
        [4., 4., 4., 4., 8.]])

Call after zeroing
 tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])
